### ISSUE TITLE
Remove the "background" permission

### ISSUE THREAD

**Issue by bzaar** [morpherltd/russiangram-chrome-extension#1]
Update the extension so that it does not require the [background](https://github.com/morpherltd/russiangram-chrome-extension/blob/main/manifest.json#L13) permission. Users are getting suspicious that the extension might be collecting personal data.

**Comment by masterWeber** [comment]
Background permission is not required.

![Screenshot from 2021-03-10 16-36-52](https://user-images.githubusercontent.com/47494224/110638019-1a9a7980-81bf-11eb-805c-f0c243f4130d.png)
