### ISSUE TITLE
Jypiter notebook menus not working

### ISSUE THREAD

**Issue by bzaar** [morpherltd/russiangram-chrome-extension#5]
The extension causes Jypiter notebook menus to stop working.

E.g. open this notebook: 

1. Go to https://jupyter.org/try
2. Click Try Classic Notebook

Menus open when clicked:

![image](https://user-images.githubusercontent.com/4028922/112633369-2f1e7900-8e31-11eb-8a8c-8a0f681f9071.png)

When the [RussianGram extension](https://chrome.google.com/webstore/detail/russiangram/bidcnmfhffpamjhgkemdmjdmnchjnmdf) is installed/enabled, menus stop working, even before the Matryoshka button is clicked.

**Comment by Curiouslynx** [comment]
Привет, если нужна помощь с расширением - сообщи свои контакты

**Comment by bzaar** [comment]
@Curiouslynx, да, нужна. Skype: serge_slepov.
